### ISSUE TITLE
How to use this for previous contests?

### ISSUE THREAD

**Issue by atiabjobayer** [anurudhp/cfutils#1]
I tried the script for an old contest. Then run it using resolver. It gave an error saying no submission found. Then I checked the JSON and there was no submission indeed.

What to do if I want to test it using a cf contest that has already happened?

**Comment by anurudhp** [comment]
Could you tell me which contest you used? I've only tested this for public gym contests, not sure if it works for standard CF ones.

**Comment by anurudhp** [comment]
stale issue, and API has been upgraded.
